export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESSED = 'USER_LOGIN_SUCCESSED';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';

export const USER_CREATE_REQUEST = 'USER_CREATE_REQUEST';
export const USER_CREATE_SUCCESSED = 'USER_CREATE_SUCCESSED';
export const USER_CREATE_FAILED = 'USER_CREATE_FAILED';